name: Ledgr
options:
  bundleIdPrefix: com.popand
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""

targets:
  Ledgr:
    type: application
    platform: iOS
    sources:
      - path: Ledgr
        excludes:
          - "Preview Content/**"
    settings:
      base:
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_NSCameraUsageDescription: "Ledgr needs camera access to photograph receipts."
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "Ledgr needs photo library access to select receipt images."
        PRODUCT_BUNDLE_IDENTIFIER: com.popand.Ledgr
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
