name: Ledgr
options:
  bundleIdPrefix: com.popand
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""

packages:
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "8.0.0"

targets:
  Ledgr:
    type: application
    platform: iOS
    sources:
      - path: Ledgr
        excludes:
          - "Preview Content/**"
    dependencies:
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift
    info:
      path: Ledgr/Resources/Info.plist
      properties:
        GIDClientID: "758203290065-pm6ml5j2dopeeesvh9mrf11gfoeg8or1.apps.googleusercontent.com"
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - "com.googleusercontent.apps.758203290065-pm6ml5j2dopeeesvh9mrf11gfoeg8or1"
        NSCameraUsageDescription: "Ledgr needs camera access to photograph receipts."
        NSPhotoLibraryUsageDescription: "Ledgr needs photo library access to select receipt images."
    settings:
      base:
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Ledgr/Resources/Info.plist
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        PRODUCT_BUNDLE_IDENTIFIER: com.popand.Ledgr
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
